---
# tasks file for ansible-role-teleport-cli

- name: Include OS specific variables.
  ansible.builtin.include_vars: "{{ ansible_facts['system'] }}.yml"

- name: Install teleport cli with .deb or .rpm
  ansible.builtin.include_tasks: "setup-rpm-deb-pkg.yml"
  when: __teleport_bin_install | bool

- name: Install teleport cli bin
  ansible.builtin.include_tasks: "setup-{{ ansible_facts['system'] }}.yml"
  when: not __teleport_bin_install | bool
