---
- name: Verify
  hosts: all
  tasks:
    - name: Linux | teleport cli should be functionnal
      ansible.builtin.command: teleport version
      register: teleport_result

    - name: Linux | tsh cli should be functionnal
      ansible.builtin.command: tsh version
      register: tsh_result

    - name: Linux | tctl cli should be functionnal
      ansible.builtin.command: tctl version
      register: tctl_result

    - name: Linux | tbot cli should be functionnal
      ansible.builtin.command: tbot version
      register: tbot_result

    - name: Linux | Verify commands outputs
      ansible.builtin.assert:
        that:
          - teleport_result.rc == 0
          - tsh_result.rc == 0
          - tctl_result.rc == 0
          - tbot_result.rc == 0
        success_msg: "All tests passed"
